#! /bin/sh
# $Format:%H% d$

NAME=spamhausfeed
VER="$1"
RELEASE="release-$VER"

if [ -z "$VER" ]; then
  echo "Syntax: $0 <version>"
  exit 1
fi

git tag $RELEASE

git archive --format=tar --prefix=$NAME-$VER/ $RELEASE | gzip > $NAME-$VER.tar.gz

